name: CI
on:
  push:
    branches: [ "test_ci" ]


  workflow_dispatch:

jobs:
  display:
    runs-on: ubuntu-latest
    env:
      platform: Azure
      region: west
      profile_path: profile/

    steps:
      - name: Display custom environmental variables
        if: ${{ env.platform == 'Azure'}} #must use this if want to run outside a run comman (e.g. in 'if' statement)
        #can use $region format only if it is a run command like below
        run: |
          echo "The platform is ${{ env.platform }}" 
          echo "The region is $region"
  
      - name: Display GH Default env variables #exploring default GH variables
        run: |
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List all ORIGINAL files
        run: ls

      - name: Install Python #Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Python Script #Creates a new file
        run: python create_file.py

      - name: List all ADDED files #lists all added files
        run: ls


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: print a value
        run: echo "Hello from another job"
